services:
  dind:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - docker-data:/var/lib/docker
    networks:
      - jenkins
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins_data:/var/jenkins_home
      - docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    depends_on:
      - dind
    restart: unless-stopped

volumes:
  jenkins_data:
  docker-data:
  docker-certs:

networks:
  jenkins:
    driver: bridge
